export const mockData = [
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '[]',
    workflow_status: 'review',
    background_content: {
      objectType: 'image',
      Title: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'check-comment',
    title: 'check comment',
    description: 'check comment',
    page: 'check-comment',
    current_page_url: '/check-comment',
    parent_page_url: '/',
    last_modified_by: 'rishabh srivastava',
    author: 'Rahul Kaushal',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-25T13:18:01.160Z',
    last_modification_date: '2023-08-25T13:18:01.160Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/check-comment/check-comment[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/check-comment',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '[]',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Title: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'check-comment',
    title: 'check comment',
    description: 'check comment',
    page: 'check-comment',
    current_page_url: '/check-comment',
    parent_page_url: '/',
    last_modified_by: 'Rahul Kaushal',
    author: 'Rahul Kaushal',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-25T13:11:34.343Z',
    last_modification_date: '2023-08-25T13:11:34.343Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/check-comment/check-comment',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/check-comment',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: 'check',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Title: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'check',
    title: 'check',
    description: 'check',
    page: 'check',
    current_page_url: '/check',
    parent_page_url: '/',
    last_modified_by: 'Rahul Kaushal',
    author: 'Rahul Kaushal',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-21T10:18:32.177Z',
    last_modification_date: '2023-08-21T10:18:32.177Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path: '/content/documents/hclplatformx/en/quiz/check/check[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/check',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '[]',
    workflow_status: 'review',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Title: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'apollo-11-mission',
    title: 'Apollo 11 Mission',
    description:
      'Mission Objective\nThe primary objective of Apollo 11 was to complete a national goal set by President John F. Kennedy on May 25, 1961: perform a crewed lunar landing and return to Earth.',
    page: 'apollo-11-mission',
    current_page_url: '/apollo-11-mission',
    parent_page_url: '/',
    last_modified_by: 'Rahul Kaushal',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-21T09:30:22.876Z',
    last_modification_date: '2023-08-21T09:30:22.876Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/apollo-11-mission/apollo-11-mission[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/apollo-11-mission',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Albania'],
    short_description: 'healthy fruit',
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[\\"healthy-fruit\\"]"',
    background_content: {
      objectType: 'image',
      Url: '1691589604345/public/jpeg/wef-nvsfoundation-hero',
      Title: '',
      Thumbnail: '1691589604345/public/jpeg/wef-nvsfoundation-hero',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'healthy-fruit',
    title: 'healthy fruit',
    description: 'healthy fruit',
    page: 'healthy-fruit',
    current_page_url: '/healthy-fruit',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'Sunil s',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-14T12:39:37.871Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-14T12:39:34.904Z',
    last_modification_date: '2023-08-14T12:39:34.904Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-14T12:39:37.871Z',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/healthy-fruit/healthy-fruit[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/healthy-fruit',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: 'Physical Geography Quiz',
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"healthy-fruit\\",\\"dsdsa\\",\\"in-local-seo-efforts-what-need-to-optimize-in-google-my-business\\",\\"what-is-javascript\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://dev.dam.hcl-x.com/server/api/core/bitstreams/ccb876e5-3720-4909-8c16-3aa2175831f7/content',
      Title: '',
      Thumbnail:
        'https://dev.dam.hcl-x.com/server/api/core/bitstreams/ccb876e5-3720-4909-8c16-3aa2175831f7/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'physical-geography-quiz',
    title: 'Physical Geography Quiz',
    description: 'Physical Geography Quiz',
    page: 'physical-geography-quiz',
    current_page_url: '/physical-geography-quiz',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-11T11:52:54.544Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-11T11:52:45.898Z',
    last_modification_date: '2023-08-11T11:52:45.898Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-11T11:52:54.544Z',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/physical-geography-quiz/physical-geography-quiz[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/physical-geography-quiz',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Quiz'],
    short_description: 'dfdsfd',
    workflow_status: '[]',
    display_scores: 'Percentage',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"the-parliament-of-india-cannot-be-regarded-as-a-sovereign-body-because\\",\\"lucknow-is-located-in-which-state\\",\\"new-lang-question\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/b5a47e06-0601-42b4-bdda-2bb9d0c96982/content',
      Title: '',
      Thumbnail:
        'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/b5a47e06-0601-42b4-bdda-2bb9d0c96982/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'reere',
    title: 'Indian Politics - Indian Politics',
    description: 'ds',
    page: 'reere',
    current_page_url: '/reere',
    parent_page_url: '/',
    last_modified_by: 'Sunil s',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'Sunil',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-11T09:14:09.805Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-11T09:14:07.799Z',
    last_modification_date: '2023-08-11T09:14:07.799Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-11T09:14:09.805Z',
    jcr_path: '/content/documents/hclplatformx/en/quiz/reere/reere[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/reere',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Cristiano Ronaldo', 'Gareth Bale'],
    short_description: 'general knowledge',
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"in-local-seo-efforts-what-need-to-optimize-in-google-my-business\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://dev.dam.hcl-x.com/server/api/core/bitstreams/d2b99e79-0d11-4d6d-b115-257910810b54/content',
      Title: '',
      Thumbnail:
        'https://dev.dam.hcl-x.com/server/api/core/bitstreams/d2b99e79-0d11-4d6d-b115-257910810b54/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'general-knowledge',
    title: 'general knowledgeaa',
    description: 'general knowledge',
    page: 'general-knowledge',
    current_page_url: '/general-knowledge',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-08T13:38:37.788Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-10T13:34:54.351Z',
    last_modification_date: '2023-08-10T13:34:54.351Z',
    page_state: 'draft',
    last_published_date: '2023-08-08T13:38:37.788Z',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/general-knowledge/general-knowledge[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/general-knowledge',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['archery', 'basketball', 'PDF'],
    short_description:
      "If you want to make your next pub quiz or games night all the more enjoyable, then see what Mentimeter's quiz maker can do for you!",
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[\\"best-cricket-team\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://dev.dam.hcl-x.com/server/api/core/bitstreams/668597d5-d86d-4340-b052-00242701bd65/content',
      Title: '',
      Thumbnail:
        'https://dev.dam.hcl-x.com/server/api/core/bitstreams/668597d5-d86d-4340-b052-00242701bd65/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'genral-knowledge',
    title: 'Genral Knowledge',
    description:
      "If you want to make your next pub quiz or games night all the more enjoyable, then see what Mentimeter's quiz maker can do for you!",
    page: 'genral-knowledge',
    current_page_url: '/genral-knowledge',
    parent_page_url: '/',
    last_modified_by: 'Rahul Kaushal',
    author: 'Rahul Kaushal',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-10T13:29:03.931Z',
    last_modification_date: '2023-08-10T13:29:03.931Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/genral-knowledge/genral-knowledge[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/genral-knowledge',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '[]',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Url: '',
      Title: '',
      Thumbnail: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'fbdfd',
    title: 'fbdfdd',
    description: 'dfb',
    page: 'fbdfd',
    current_page_url: '/fbdfd',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-10T08:57:23.387Z',
    last_modification_date: '2023-08-10T08:57:23.387Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path: '/content/documents/hclplatformx/en/quiz/fbdfd/fbdfd[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/fbdfd',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Mesut Özil'],
    short_description: 'Team',
    workflow_status: '[]',
    display_scores: 'Percentage',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[\\"best-cricket-team\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://dev.dam.hcl-x.com/server/api/core/bitstreams/b4828583-d9a3-4a08-a51e-661cc0e397ca/content',
      Title: '',
      Thumbnail:
        'https://dev.dam.hcl-x.com/server/api/core/bitstreams/b4828583-d9a3-4a08-a51e-661cc0e397ca/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'team',
    title: 'Team1111',
    description: 'Team',
    page: 'team',
    current_page_url: '/team',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'Sunil s',
    user_action_info: {
      publishByDetails: {
        name: 'Sunil',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-09T07:34:40.583Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-10T08:56:46.753Z',
    last_modification_date: '2023-08-10T08:56:46.753Z',
    page_state: 'draft',
    last_published_date: '2023-08-09T07:34:40.583Z',
    published_date: '',
    jcr_path: '/content/documents/hclplatformx/en/quiz/team/team[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/team',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Kevin Durant'],
    short_description: 'Javascript Quiz',
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[\\"what-is-javascript\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://dev.dam.hcl-x.com/server/api/core/bitstreams/8d1553a1-8518-4478-a6db-119021e00e22/content',
      Title: '',
      Thumbnail:
        'https://dev.dam.hcl-x.com/server/api/core/bitstreams/8d1553a1-8518-4478-a6db-119021e00e22/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'javascript-quiz',
    title: 'Javascript Quizs',
    description: 'Javascript Quiz',
    page: 'javascript-quiz',
    current_page_url: '/javascript-quiz',
    parent_page_url: '/',
    last_modified_by: 'Sunil s',
    author: 'Sunil s',
    user_action_info: {
      publishByDetails: {
        name: 'Sunil',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-09T07:09:00.889Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-09T07:10:17.791Z',
    last_modification_date: '2023-08-09T07:10:17.791Z',
    page_state: 'draft',
    last_published_date: '2023-08-09T07:09:00.889Z',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/javascript-quiz/javascript-quiz[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/javascript-quiz',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Cristiano Ronaldo'],
    short_description: 'descritiopn',
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[\\"what-is-javascript\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://dev.dam.hcl-x.com/server/api/core/bitstreams/36d7680e-15f8-431e-b06f-c8b22949e10d/content',
      Title: '',
      Thumbnail:
        'https://dev.dam.hcl-x.com/server/api/core/bitstreams/36d7680e-15f8-431e-b06f-c8b22949e10d/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'general-quiz',
    title: 'General Quiz',
    description: 'General Quiz',
    page: 'general-quiz',
    current_page_url: '/general-quiz',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-09T06:44:58.494Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-09T06:45:20.087Z',
    last_modification_date: '2023-08-09T06:45:20.087Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-09T06:44:58.494Z',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/general-quiz/general-quiz[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/general-quiz',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Quiz'],
    short_description: 'Question related to Indian Geoagraphy',
    workflow_status: 'author pending',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"the-principal-copper-deposits-of-india-lie-in-which-of-the-following-places-\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/c1606bc0-a476-426a-956f-5e810d5e55f8/content',
      Title: '',
      Thumbnail:
        'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/c1606bc0-a476-426a-956f-5e810d5e55f8/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'general-knowledge-indian-geography-',
    title: 'General Knowledge Indian Geography',
    description: 'Question related to Indian Geaography',
    page: 'general-knowledge-indian-geography-',
    current_page_url: '/general-knowledge-indian-geography-',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-08T15:53:06.953Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-08T15:53:27.618Z',
    last_modification_date: '2023-08-08T15:53:27.618Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-08T15:53:06.953Z',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/general-knowledge-indian-geography-/general-knowledge-indian-geography-[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/general-knowledge-indian-geography-',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Quiz'],
    short_description: 'Question related to Indian Geography',
    workflow_status: '[]',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"the-principal-copper-deposits-of-india-lie-in-which-of-the-following-places-\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/c1606bc0-a476-426a-956f-5e810d5e55f8/content',
      Title: '',
      Thumbnail:
        'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/c1606bc0-a476-426a-956f-5e810d5e55f8/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'copy-of-general-knowledge-indian-geography',
    title: 'Copy of General Knowledge Indian Geography',
    description: 'Question related to Indian Geography',
    page: 'copy-of-general-knowledge-indian-geography',
    current_page_url: '/copy-of-general-knowledge-indian-geography',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-08T13:10:06.442Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-08T13:10:27.276Z',
    last_modification_date: '2023-08-08T13:10:27.276Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-08T13:10:06.442Z',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/copy-of-general-knowledge-indian-geography/copy-of-general-knowledge-indian-geography[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/copy-of-general-knowledge-indian-geography',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '[]',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Url: '',
      Title: '',
      Thumbnail: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'wfefwewf',
    title: 'geography of india',
    description: 'eefcs',
    page: 'wfefwewf',
    current_page_url: '/wfefwewf',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-07T06:10:33.511Z',
    last_modification_date: '2023-08-07T06:10:33.511Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path: '/content/documents/hclplatformx/en/quiz/wfefwewf/wfefwewf[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/wfefwewf',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Cristiano Ronaldo', 'Afghanistan', 'Articles'],
    short_description: 'test',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"the-principal-copper-deposits-of-india-lie-in-which-of-the-following-places-\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/c1606bc0-a476-426a-956f-5e810d5e55f8/content',
      Title: '',
      Thumbnail:
        'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/c1606bc0-a476-426a-956f-5e810d5e55f8/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'fan-facing-quiz-issue',
    title: 'fan-facing-quiz-issue',
    description: 'test',
    page: 'fan-facing-quiz-issue',
    current_page_url: '/fan-facing-quiz-issue',
    parent_page_url: '/',
    last_modified_by: 'manish kumar',
    author: 'manish kumar',
    user_action_info: {
      publishByDetails: {
        name: 'manish',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-08-01T12:22:16.649Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'published',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-08-01T12:21:06.441Z',
    last_modification_date: '2023-08-01T12:21:06.441Z',
    page_state: 'published',
    last_published_date: '',
    published_date: '2023-08-01T12:22:16.649Z',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/fan-facing-quiz-issue/fan-facing-quiz-issue[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/fan-facing-quiz-issue',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Url: '',
      Title: '',
      Thumbnail: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'ms-dhoni',
    title: 'TitleDescription',
    description: 'ms dhoni',
    page: 'ms-dhoni',
    current_page_url: '/',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-08-01T07:45:26.787Z',
    last_modification_date: '2023-08-01T07:45:26.787Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path: '/content/documents/hclplatformx/en/quiz/ms-dhoni/ms-dhoni[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/ms-dhoni',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: [],
    short_description: '[]',
    workflow_status: 'draft',
    display_scores: 'Count',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions: '"[]"',
    background_content: {
      objectType: 'image',
      Url: '',
      Title: '',
      Thumbnail: '',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'xbfxcbffb',
    title: 'xbfxcbffb',
    description: 'xfbxcfbc',
    page: 'xbfxcbffb',
    current_page_url: '/xbfxcbffb',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: false,
    tag_name: 'Quiz',
    modification_date: '2023-07-31T12:09:18.195Z',
    last_modification_date: '2023-07-31T12:09:18.195Z',
    page_state: 'draft',
    last_published_date: '',
    published_date: '',
    jcr_path: '/content/documents/hclplatformx/en/quiz/xbfxcbffb/xbfxcbffb[2]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/xbfxcbffb',
  },
  {
    analytics_enable: false,
    seo_enable: false,
    tags: ['Quiz'],
    short_description: 'dfdsfd',
    workflow_status: 'draft',
    display_scores: 'Percentage',
    result_range_1: 'A winner never stops trying',
    result_range_2: 'You cannot be a winner without maturity and consistency',
    result_range_3: "In everything we do there's a winner and a loser",
    result_range_4: "That's how I live my life, with belief. I am a winner",
    questions:
      '"[\\"the-parliament-of-india-cannot-be-regarded-as-a-sovereign-body-because\\",\\"lucknow-is-located-in-which-state\\",\\"new-lang-question\\"]"',
    background_content: {
      objectType: 'image',
      Url: 'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/b5a47e06-0601-42b4-bdda-2bb9d0c96982/content',
      Title: '',
      Thumbnail:
        'https://platx-dspace-dev.fanuep.com/server/api/core/bitstreams/b5a47e06-0601-42b4-bdda-2bb9d0c96982/content',
      Color: '',
    },
    options_compound_fields: [],
    schduled_publish_trigger_datetime: null,
    schduled_unPublish_trigger_datetime: null,
    name: 'copy-of-indian-politics',
    title: 'copy-of-indian-politics test',
    description: 'ds',
    page: 'copy-of-indian-politics',
    current_page_url: '/copy-of-indian-politics',
    parent_page_url: '/',
    last_modified_by: 'vikalp rai saxena',
    author: 'vikalp rai saxena',
    user_action_info: {
      publishByDetails: {
        name: 'vikalp',
        email: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '2023-07-31T09:34:23.264Z',
      },
      unpublishByDetails: {
        email: '',
        name: '',
        timeZone: 'Asia/Kolkata',
        pubUnpubDateTime: '',
      },
    },
    status: 'draft',
    is_published: true,
    tag_name: 'Quiz',
    modification_date: '2023-07-31T09:39:15.453Z',
    last_modification_date: '2023-07-31T09:39:15.453Z',
    page_state: 'draft',
    last_published_date: '2023-07-31T09:34:23.264Z',
    published_date: '',
    jcr_path:
      '/content/documents/hclplatformx/en/quiz/copy-of-indian-politics/copy-of-indian-politics[3]',
    jcr_score: '11833',
    path: '/content/documents/hclplatformx/en/quiz/copy-of-indian-politics',
  },
];
