apiVersion: v1
data:
  REACT_APP_ANALYTICS_PROVIDER: googleTagManager
  REACT_APP_API_URI: https://marvericks.api.hcl-x.com/platform-x/
  REACT_APP_APM_ENVIRONMENT: mavericks
  REACT_APP_APM_SERVER_URL: https://platx-apm-server-dev.hcl-x.com
  REACT_APP_APM_TRACING: 'false'
  REACT_APP_AUTHOR_URI: https://marvericks.console.hcl-x.com/
  REACT_APP_BLOG_API_URI: https://blogging.hcl-x.com/platform-x/
  REACT_APP_BUCKET_NAME: cropped_image_public
  REACT_APP_CHAT_GPT_PROMPT: Please write 3 paragraph article about
  REACT_APP_CHATGPT_API_URI: https://marvericks.api.hcl-x.com/platform-x/api/v1/web/
  REACT_APP_CLIENT_ID: react
  REACT_APP_COMPONENT_THEME: HclXPrelemTheme
  REACT_APP_DEFAULT_IMAGE: machine_assets/1691655304773/public/png/Group_6705-03.png
  REACT_APP_DELIVERY_URI: https://marvericks.delivery.hcl-x.com/platform-x/
  REACT_APP_DSPACE_IMAGES_UUID: c03888bc-d518-4549-a6b1-c51ddf7b4969
  REACT_APP_DSPACE_URI: https://dev.dam.hcl-x.com/
  REACT_APP_DSPACE_VIDEOS_UUID: 080fc67d-b813-49e5-9c2c-34a2790d789b
  REACT_APP_FOOTER: Footer
  REACT_APP_FOOTER_THEME: HclXPrelemTheme
  REACT_APP_GA_ID: G-69NYDPVH94
  REACT_APP_GCP_URL: https://storage.googleapis.com
  REACT_APP_GOOGLE_SEARCH_VERIFICATION: GA-12345
  REACT_APP_GRANT_TYPE: authorization_code
  REACT_APP_GRAPHQL_URI: https://marvericks.api.hcl-x.com/platform-x/v1/authoring/gateway
  REACT_APP_GTM_ID: GTM-WGS9WRS
  REACT_APP_HEADER: Header
  REACT_APP_HEADER_THEME: HclXPrelemTheme
  REACT_APP_KEYCLOAK_URI: https://dev.idp.hcl-x.com
  REACT_APP_NAV_ICON_1: https://dev.dam.hcl-x.com/server/api/core/bitstreams/373a4dc5-c608-404a-89ff-8b2644240f45/content
  REACT_APP_NAV_ICON_2: https://dev.dam.hcl-x.com/server/api/core/bitstreams/269e9b4a-41e4-444f-8e09-af7dc822b581/content
  REACT_APP_NAV_ICON_3: https://dev.dam.hcl-x.com/server/api/core/bitstreams/58e0164c-29fc-4bdd-a9c5-67bc7797c3f7/content
  REACT_APP_NAV_ICON_4: https://dev.dam.hcl-x.com/server/api/core/bitstreams/d387c7c3-3dae-49be-ad8e-3b4e247f6ebb/content
  REACT_APP_NAV_ICON_5: https://dev.dam.hcl-x.com/server/api/core/bitstreams/6244eeaa-6df4-449d-865f-eaf80aba3ffc/content
  REACT_APP_NAV_ICON_6: https://dev.dam.hcl-x.com/server/api/core/bitstreams/333642fb-752d-499f-aeba-481effa2caf5/content
  REACT_APP_NAV_ICON_7: https://dev.dam.hcl-x.com/server/api/core/bitstreams/f502bca9-baae-4964-a398-6fe2c4e54945/content
  REACT_APP_NAV_ICON_8: https://dev.dam.hcl-x.com/server/api/core/bitstreams/42085059-0636-4b57-acb1-fbc98489331d/content
  REACT_APP_NAV_ICON_9: https://dev.dam.hcl-x.com/server/api/core/bitstreams/d29e2a9c-446f-4a1e-b0a0-fc67a28f4265/content
  REACT_APP_NAV_ICON_10: https://dev.dam.hcl-x.com/server/api/core/bitstreams/e0056513-65b5-45ed-a381-c1b82619f368/content
  REACT_APP_NAV_ICON_11: https://dev.dam.hcl-x.com/server/api/core/bitstreams/048e9e07-1f04-4df9-813b-332c37f0f8aa/content
  REACT_APP_NAV_ICON_12: https://dev.dam.hcl-x.com/server/api/core/bitstreams/b5ca8fab-9a5d-4746-8441-15038ef5fbbf/content
  REACT_APP_PUBLISH_URI: https://marvericks.hcl-x.com/
  REACT_APP_REALM: platform-x
  REACT_APP_REDIRECT_URI: https://marvericks.console.hcl-x.com/en/
  REACT_APP_PRELEM_THEME: dark
  REACT_APP_BASE_URL: https://marvericks.console.hcl-x.com
kind: ConfigMap
metadata:
  name: hep-authoring-ui-config
  namespace: mavericks
