export type CreateContentHeaderProps = {
  id?: any;
  previewButton?: any;
  returnBack?: any;
  publish?: any;
  saveorPublish?: any;
  handelPreview?: any;
  editText?: string;
  createText?: string;
  toolTipText?: any;
  isQuiz?: any;
  publishButton?: any;
  saveButton?: any;
  publishText?: any;
  saveText?: any;
  previewText?: any;
  saveVariant?: any;
  showPreview?: boolean;
  className?: string;
  category?: string;
  subCategory?: string | string[];
  workflow?: any;
  timerState?: any;
  lastmodifiedDate?: any;
  setEnableWorkflowHistory?: (boolean) => void;
  createComment?: any;
  setIsFeatured?: any;
  isFeatured?: any;
};
