export type VodInstance = {
  Page: string
  Description: string
  ShortDescription: string
  AccountId: string
  PlayerID: string
  VideoId: string
  PlayerType: string
  Title: string
  CurrentPageURL: string
  ParentPageURL: string
  Page_State: string
  Thumbnail?: string
  DsapceVideoUrl?: string
  Author?: string
  Poster: string
  Tags: []
  IsEdit: boolean
  SeoEnable: boolean
  AnalyticsEnable: boolean
  RobotTxt: boolean
  SiteMap: boolean
  Page_CreatedBy: string
  Page_LastModifiedBy: string
  Page_PublishedBy: string
  Analytics: string
  Others: string
  StructureData: string
  PageSettings: any
  IsConfirm: boolean
}
