import { Content } from "@platformx/content";
import {
    ArticleIcon,
    CourseIcon,
    EventsIcon,
    PollIcon,
    QuizIcon,
    VideoIcon
} from '@platformx/utilities';
export const ContentRoutes = [{
    url: "",
    Title: "content",
    id: "content",
    Menu: [
        {
            MenuName: "Article",
            Icon: ArticleIcon,
            url: "/content/article",
            id: "article",
            category: "content",
            subCategory: "article",
            component: <Content></Content>,
        },
        {
            MenuName: "VOD",
            Icon: VideoIcon,
            url: "/content/vod",
            category: "content",
            subCategory: "vod",
            id: "vod",
            component: <Content></Content>,
        },
        {
            MenuName: "Quiz",
            Icon: QuizIcon,
            url: "/content/quiz",
            category: "content",
            subCategory: "quiz",
            id: "quiz",
            component: <Content></Content>,
        },
        {
            MenuName: "Poll",
            Icon: PollIcon,
            url: "/content/poll",
            category: "content",
            subCategory: "poll",
            id: "poll",
            component: <Content></Content>,
        },
        {
            MenuName: "Events",
            Icon: EventsIcon,
            url: "/content/event",
            category: "content",
            subCategory: "event",
            id: "events",
            component: <Content></Content>,
        },
        {
            MenuName: "Courses",
            Icon: CourseIcon,
            url: "/content/course",
            category: "content",
            subCategory: "",
            id: "course",
            component: <Content></Content>,
        },
        // {
        //   MenuName: 'Community',
        //   Icon: Community,
        //   url: '/content/community',
        //   category: 'content',
        //   subCategory: '',
        //   id: 'Community',
        //   component:<Content></Content> ,
        // },
    ],
},
];