import { t } from "i18next";
import { NewQuizType, QuizType } from "./Quiz.types";

export const createInitialQuizState = (): QuizType => ({
    title: "",
    short_title: "",
    short_description: "",
    description: "",
    imagevideoURL: "",
    thumbnailURL: "",
    socialShareImgURL: "",
    titleSocialShare: "",
    descriptionSocialShare: "",
    tagsSocialShare: [],
    analytics_enable: true,
    impression: true,
    contentInsight: false,
    seo_enable: true,
    seoShared: true,
    scoreBy: t("count"),
    tags: [],
    questions: [],
    result_range_1: t("quiz_quotes_quote1"),
    result_range_2: t("quiz_quotes_quote2"),
    result_range_3: t("quiz_quotes_quote3"),
    result_range_4: t("quiz_quotes_quote4"),
    is_schedule_publish: false,
    schedule_publish_datetime: "",
    is_schedule_unpublish: false,
    schedule_unpublish_datetime: "",
    original_image: {},
    published_images: [],
});


export const createNewQuiz = (username: string): NewQuizType => ({
    CommonFields: {
        page: "",
        title: "",
        short_title: "",
        description: "",
        short_description: "",
        category: "Quiz",
        site_name: "PlatX",
        page_state: "",
        is_edit: false,
        seo_enable: true,
        analytics_enable: true,
        robot_txt: false,
        sitemap: false,
        analytics: "",
        others: "",
        structure_data: "",
        creationDate: new Date().toISOString(),
        modificationDate: new Date().toISOString(),
        tags: [],
        createdBy: username,
        parent_page_url: "/",
        current_page_url: "",
        page_lastmodifiedby: username,
        settings: {},
    },
    ObjectFields: {
        questions: [],
        background_content: {
            objectType: "image",
            Url: "",
            Title: "",
            Thumbnail: "",
            Color: "black",
        },
        display_scores: "Count",
        result_range_1: t("quiz_quotes_quote1"),
        result_range_2: t("quiz_quotes_quote2"),
        result_range_3: t("quiz_quotes_quote3"),
        result_range_4: t("quiz_quotes_quote4"),
    },
});