export const initialObject = () => {
  const previewObject = {
    Page: '',
    SiteName: '',
    SubTitle: null,
    Title: '',
    Banner: '',
    Description: '',
    ContentType: '',
    Category: '',
    ParentPageURL: '',
    CurrentPageURL: '',
    Page_CreatedBy: '',
    Page_PublishedBy: '',
    IsEdit: false,
    SeoEnable: true,
    AnalyticsEnable: true,
    RobotTxt: false,
    SiteMap: false,
    Others: null,
    Analytics: null,
    StructureData: '',
    DevelopedBy: '',
    DevelopedDate: '',
    Page_State: '',
    UserActionInfo: '',
    Links: [],
    LinkTags: [],
    creationDate: '',
    LastModificationDate: '',
    Tag: [],
  };
  return previewObject;
};
