name: ci-cd

on:
  push:
    branches:
      - develop
      - qa
      - master
      - xerox_stg
      - xerox_master
      - stg
      - x_site_live
      - mavericks_dev
      - marvels_dev
      - kiwi_dev
      - x_site_qa

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "CLUSTER_NAME=GKE_CLUSTER_$(echo ${{ github.ref_name }} | tr  '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=IMAGE_NAME_$(echo ${{ github.ref_name }} | tr  '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          echo "PROJECT_ID=PROJECT_ID_$(echo ${{ github.ref_name }} | tr  '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
          # Add other environment variables as needed

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets[env.SERVICE_ACCOUNT_KEY] }}
          project_id: ${{ secrets[env.PROJECT_ID] }}

      - name: Authenticate with GKE
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets[env.WORKLOAD_IDENTITY_PROVIDER] }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: 'access_token'

      # Add steps for deploying Configmaps based on branches

      - name: Build Docker image
        run: docker build --tag "gcr.io/${{ secrets[env.PROJECT_ID] }}/${{ secrets[env.IMAGE_NAME] }}:${{ github.run_number }}" .

      - name: Push Docker image to GCR
        run: |
          gcloud auth configure-docker --quiet
          docker push "gcr.io/${{ secrets[env.PROJECT_ID] }}/${{ secrets[env.IMAGE_NAME] }}:${{ github.run_number }}"

      # Add steps for deploying Configmaps based on branches

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.nx-cache
          key: ${{ runner.os }}-nx-${{ hashFiles('nx.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Install Nx CLI
        run: npm install -g @nrwl/nx

      - name: Build affected libraries
        run: nx affected --target=build --base=main --head=$GITHUB_SHA

      # Add steps for deploying Docker image to GKE clusters based on branches

      - name: Deploy Configmap on stage branch
        if: ${{ github.ref == 'refs/heads/stg' }}
        run: kubectl apply -f ./kubernetes/configmaps/hep-authoring-ui-config-stg.yaml

      - name: Deploy Configmap on x_site_qa branch
        if: ${{ github.ref == 'refs/heads/x_site_qa' }}
        run: kubectl apply -f ./kubernetes/configmaps/hep-authoring-ui-config-qa.yaml

      - name: Deploy Configmap on live branch
        if: ${{ github.ref == 'refs/heads/x_site_live' }}
        run: |
          echo ${{ secrets.HEP_AUTHORING_UI_LIVE }} | base64 --decode > hep-authoring-ui-config-live.yaml
          kubectl apply -f hep-authoring-ui-config-live.yaml

      # Add steps for deploying Docker image to GKE clusters based on branches

      - name: Deploy to GKE (dev, qa, master, etc.)
        if: |
          contains('refs/heads/kiwi_dev refs/heads/marvels_dev refs/heads/mavericks_dev refs/heads/develop refs/heads/qa refs/heads/master refs/heads/xerox_stg refs/heads/xerox_master', github.ref)
        run: |
          # Add deployment steps for the corresponding branches

      - name: Deploy to GKE (stg, x_site_live, x_site_qa)
        if: |
          contains('refs/heads/x_site_live refs/heads/x_site_qa refs/heads/stg', github.ref)
        run: |
          # Add deployment steps for the corresponding branches
          - name: Deploy React App on develop and qa branches
        if: |
          contains('refs/heads/develop refs/heads/qa', github.ref)
        run: |
          nx run authoring-web:deploy

      - name: Deploy React App on master branch
        if: |
          contains('refs/heads/master', github.ref)
        run: |
          nx run authoring-web:deploy-prod

      - name: Deploy React App on stg branch
        if: |
          contains('refs/heads/stg', github.ref)
        run: |
          nx run authoring-web:deploy-stg

      - name: Deploy React App on x_site_live branch
        if: |
          contains('refs/heads/x_site_live', github.ref)
        run: |
          nx run authoring-web:deploy-live

      - name: Deploy React App on mavericks_dev branch
        if: |
          contains('refs/heads/mavericks_dev', github.ref)
        run: |
          nx run authoring-web:deploy-dev

      - name: Deploy React App on marvels_dev branch
        if: |
          contains('refs/heads/marvels_dev', github.ref)
        run: |
          nx run authoring-web:deploy-marvels

      - name: Deploy React App on kiwi_dev branch
        if: |
          contains('refs/heads/kiwi_dev', github.ref)
        run: |
          nx run authoring-web:deploy-kiwi

      - name: Deploy React App on x_site_qa branch
        if: |
          contains('refs/heads/x_site_qa', github.ref)
        run: |
          nx run authoring-web:deploy-qa
